inherit_from:
  - .rubocop_rails.yml
  - .rubocop_rspec.yml

AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - bin/*
    - db/schema.rb
    - vendor/bundle/**/*

Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes